# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 797e02a79037ab51729228eb03fa996e2368e6e60349ca35d780b2d873346f46a7000ad30f3875db8c57e4c43fc162a1816dac2ac8488d09fa7e6768eda0281b

test:
  secret_key_base: ea45a7fab759480593101e16c13dc20fbd45d22943ddbe8b8fc75f1cb8b0205b606f3a0ed0a8ca85cd9bf72d4b59d067504fbeb578a5dc1a1213437acad3270f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
